###
# Create a new presentation
POST http://localhost:3001/api/presentations
Content-Type: application/json

{
  "name": "tests",
  "textContent": "This is a test note"
}

###

# Get all presentations
GET http://localhost:3001/api/presentations
Content-Type: application/json

###

# Get a specific note by name
GET http://localhost:3001/api/presentations/tests
Content-Type: application/json

###

# Delete a note by name
DELETE http://localhost:3001/api/presentations/Test%20Note
Content-Type: application/json
